version: '3'
services:
  provider:
    build:
      context: ./provider
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - mf-network

  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - provider
    networks:
      - mf-network

networks:
  mf-network:
    driver: bridge 